list: $/pl/tid/models/listing/columns.yaml
modelClass: Pl\Tid\Models\Listing
title: Listings
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pl/tid/listings/update/:id'
