list: $/pl/tid/models/city/columns.yaml
modelClass: Pl\Tid\Models\City
title: Cities
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pl/tid/cities/update/:id'
